# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindPaczkomat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import urllib.request as ul
from bs4 import BeautifulSoup as soup
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QFileDialog, QDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 411, 651))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.CityName = QtWidgets.QLineEdit(self.splitter)
        self.CityName.setObjectName("CityName")
        self.FindButton = QtWidgets.QPushButton(self.splitter)
        self.FindButton.setObjectName("FindButton")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.PaczkomatList = QtWidgets.QTableWidget(self.widget)
        self.PaczkomatList.setObjectName("PaczkomatList")
        self.PaczkomatList.setColumnCount(0)
        self.PaczkomatList.setRowCount(0)
        self.gridLayout.addWidget(self.PaczkomatList, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        def removeAccents(input_text):
            strange='ŮôῡΒძěἊἦëĐᾇόἶἧзвŅῑἼźἓŉἐÿἈΌἢὶЁϋυŕŽŎŃğûλВὦėἜŤŨîᾪĝžἙâᾣÚκὔჯᾏᾢĠфĞὝŲŊŁČῐЙῤŌὭŏყἀхῦЧĎὍОуνἱῺèᾒῘᾘὨШūლἚύсÁóĒἍŷöὄЗὤἥბĔõὅῥŋБщἝξĢюᾫაπჟῸდΓÕűřἅгἰშΨńģὌΥÒᾬÏἴქὀῖὣᾙῶŠὟὁἵÖἕΕῨčᾈķЭτἻůᾕἫжΩᾶŇᾁἣჩαἄἹΖеУŹἃἠᾞåᾄГΠКíōĪὮϊὂᾱიżŦИὙἮὖÛĮἳφᾖἋΎΰῩŚἷРῈĲἁéὃσňİΙῠΚĸὛΪᾝᾯψÄᾭêὠÀღЫĩĈμΆᾌἨÑἑïოĵÃŒŸζჭᾼőΣŻçųøΤΑËņĭῙŘАдὗპŰἤცᾓήἯΐÎეὊὼΘЖᾜὢĚἩħĂыῳὧďТΗἺĬὰὡὬὫÇЩᾧñῢĻᾅÆßшδòÂчῌᾃΉᾑΦÍīМƒÜἒĴἿťᾴĶÊΊȘῃΟúχΔὋŴćŔῴῆЦЮΝΛῪŢὯнῬũãáἽĕᾗნᾳἆᾥйᾡὒსᾎĆрĀüСὕÅýფᾺῲšŵкἎἇὑЛვёἂΏθĘэᾋΧĉᾐĤὐὴιăąäὺÈФĺῇἘſგŜæῼῄĊἏØÉПяწДĿᾮἭĜХῂᾦωთĦлðὩზკίᾂᾆἪпἸиᾠώᾀŪāоÙἉἾρаđἌΞļÔβĖÝᾔĨНŀęᾤÓцЕĽŞὈÞუтΈέıàᾍἛśìŶŬȚĳῧῊᾟάεŖᾨᾉςΡმᾊᾸįᾚὥηᾛġÐὓłγľмþᾹἲἔбċῗჰხοἬŗŐἡὲῷῚΫŭᾩὸùᾷĹēრЯĄὉὪῒᾲΜᾰÌœĥტ' 
            ascii_replacements='UoyBdeAieDaoiiZVNiIzeneyAOiiEyyrZONgulVoeETUiOgzEaoUkyjAoGFGYUNLCiIrOOoqaKyCDOOUniOeiIIOSulEySAoEAyooZoibEoornBSEkGYOapzOdGOuraGisPngOYOOIikoioIoSYoiOeEYcAkEtIuiIZOaNaicaaIZEUZaiIaaGPKioIOioaizTIYIyUIifiAYyYSiREIaeosnIIyKkYIIOpAOeoAgYiCmAAINeiojAOYzcAoSZcuoTAEniIRADypUitiiIiIeOoTZIoEIhAYoodTIIIaoOOCSonyKaAsSdoACIaIiFIiMfUeJItaKEISiOuxDOWcRoiTYNLYTONRuaaIeinaaoIoysACRAuSyAypAoswKAayLvEaOtEEAXciHyiiaaayEFliEsgSaOiCAOEPYtDKOIGKiootHLdOzkiaaIPIIooaUaOUAIrAdAKlObEYiINleoOTEKSOTuTEeiaAEsiYUTiyIIaeROAsRmAAiIoiIgDylglMtAieBcihkoIrOieoIYuOouaKerYAOOiaMaIoht'

            translator=str.maketrans(strange,ascii_replacements)
            return input_text.translate(translator)

        def findPaczkomat():
            self.PaczkomatList.setColumnCount(3) 
            self.PaczkomatList.setHorizontalHeaderLabels(["Symbol", "Street", "Status"])
            self.PaczkomatList.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
            self.PaczkomatList.setColumnWidth(0,100)
            self.PaczkomatList.setColumnWidth(1,200)
            self.PaczkomatList.setColumnWidth(2,75)

            city = removeAccents(self.CityName.text()).lower()
            url = 'https://inpost.pl/paczkomaty-'+city
            req = ul.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            client = ul.urlopen(req)
            htmldata = client.read()
            client.close()

            pagesoup = soup(htmldata, "html.parser")
            itemlocator = pagesoup.findAll('div', {"class":"container mb-5 list--point--container"})

            street = []
            symbol = []
            status = []

            for items in itemlocator:   
                allstreets = items.findAll('span', {"itemprop":"streetAddress"})
                allstatus = items.findAll('span', {"class":"point--status -map -available"})
                allsymbols = items.findAll('span', {"itemprop":"name"})
                for detail in range (0,len(allstreets)):
                    street.append(allstreets[detail].text.strip())
                    status.append(allstatus[detail].text.strip())
                    symbol.append(allsymbols[detail].text.strip())

                    self.PaczkomatList.setRowCount(len(allstreets))
                    self.PaczkomatList.setItem(detail, 0, QTableWidgetItem(str(symbol[detail])))
                    self.PaczkomatList.setItem(detail, 1, QTableWidgetItem(str(street[detail])))
                    self.PaczkomatList.setItem(detail, 2, QTableWidgetItem(str(status[detail])))
 
        self.FindButton.clicked.connect(findPaczkomat)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CityName.setPlaceholderText(_translate("MainWindow", "Insert city..."))
        self.FindButton.setText(_translate("MainWindow", "Find"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Find Paczkomat in your city!</p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    app.setStyle('Fusion')
    MainWindow.show()
    sys.exit(app.exec_())